name: buildr_studio
description: "A new Flutter project."
publish_to: "none"
version: 0.1.1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  anthropic_sdk_dart: ^0.0.1-dev.1
  context_menus: ^2.0.0+1
  file_picker: ^8.0.3
  fluent_ui: ^4.8.7
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_highlight: ^0.7.0
  get_it: ^7.7.0
  logger: ^2.3.0
  markdown: ^7.2.2
  markdown_widget: ^2.3.2+6
  mockito: ^5.4.4
  path: ^1.9.0
  path_provider: ^2.1.3
  provider: ^6.1.2
  re_highlight: ^0.0.3
  shared_preferences: ^2.2.3
  wiredash: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  golden_toolkit: ^0.15.0
  flutter_launcher_icons: ^0.13.1
  inno_bundle: ^0.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/tools/
    - .env

flutter_launcher_icons:
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 48 # min:48, max:256, default: 48

inno_bundle:
  id: 5d068604-f570-5319-ae9b-46315cf5a8ef
  publisher: "Code On Sunday"
  name: "buildr.studio"
  version: "0.1.0"
  description: "The AI Toolbox to Build More in Less Time"
  url: "https://buildr.studio"
  installer_icon: "windows/runner/resources/app_icon.ico"
