name: volta
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  file_picker: ^8.0.3
  fluent_ui: ^4.8.7
  flutter:
    sdk: flutter
  get_it: ^7.7.0
  mockito: ^5.4.4
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - assets/
